SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE insertUnknownTimeBLK
AS
BEGIN

DECLARE @MaxID int=(SELECT MAX(DelayGroupKey) FROM DimDelayGroup)

INSERT INTO DimBLKTime(BLKTimeKey, Description)
VALUES (-1,'Unknown/Bad')

END
GO
